LimitParam:
  name: limit
  in: query
  description: データ件数
  required: false
  schema:
    type: integer
    format: int32

PetIdParam:
  name: pet_id
  in: path
  description: pet ID
  required: true
  schema:
    type: integer
    format: int32
