name: api_test

on:
  push:

defaults:
  run:
    working-directory: api

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21
      - name: test
        run: make test
