# 自動生成タスクを反映漏れしてないかをチェックする
name: docs_gencheck

on:
  push:

jobs:
  main:
    name: gencheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docs/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: setup
        run: |
          cd api
          go run . seed # sqliteファイルを生成する
          cd ../docs
          make tbls

          make merger gengo gents

      - name: Check for changes
        run: |
          git diff
          git status -s
          test -z "$(git status -s)"
